[project]
name = "writer-team"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorlog>=6.9.0",
    "crewai>=0.118.0",
    "dotenv>=0.9.9",
    "langchain>=0.3.25",
    "langchain-cerebras>=0.5.0",
]
