defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

libvirt:
  hostname: "rhodey.lbl.gov"
  username: "odancona"
  identity_file: "~/.ssh/rhodey"
  pool_name: "scheduler_benchmark_pool"

cluster:
  name: "benchmark-cluster"
  head_nodes:
    - name: "head-node-1"
      image: "nixos-k8s-master.img"
      disk_size_gb: 16
      resources:
        - type: "cpu"
          amount: 8
          unit: "cores"
        - type: "ram"
          amount: 16384
          unit: "mb"
      network:
        name: "scheduler_benchmark_net"
        cidr: "192.168.222.0/24"
        gateway: "192.168.222.1"
      user:
        name: "odancona"
        sudo: true
        ssh_public_key_path: "~/.ssh/rhodey.pub"

  compute_nodes:
    - name: "compute-node-1"
      image: "nixos-k8s-worker.img"
      disk_size_gb: 16
      resources:
        - type: "cpu"
          amount: 2
          unit: "cores"
        - type: "ram"
          amount: 4096
          unit: "mb"
      network:
        name: "scheduler_benchmark_net"
        cidr: "192.168.222.0/24"
        gateway: "192.168.222.1"
      user:
        name: "odancona"
        sudo: true
        ssh_public_key_path: "~/.ssh/rhodey.pub"
    - name: "compute-node-2"
      image: "nixos-k8s-worker.img"
      disk_size_gb: 16
      resources:
        - type: "cpu"
          amount: 4
          unit: "cores"
        - type: "ram"
          amount: 4096
          unit: "mb"
      network:
        name: "scheduler_benchmark_net"
        cidr: "192.168.222.0/24"
        gateway: "192.168.222.1"
      user:
        name: "odancona"
        sudo: true
        ssh_public_key_path: "~/.ssh/rhodey.pub"

scheduler:
  type: "slurm"
  version: "23.02.3"
  partitions: ["compute"]
  config_options:
    SelectType: "cons_tres"
